
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND BODY CLOSE_CIRC_BR CLOSE_SHAPED_BR COLON COMMENT_ONELINE COMMENT_ONE_LINE COMPARISON CONSTRUCT DIVIDE DOLLAR EQUAL FUNCTION FUNCTION_DEFINITION FUNCTION_NAME LOGICAL_OR NOT NUMBER OPEN_CIRC_BR OPEN_SHAPED_BR OPERATOR_ASSIGNMENT OR QUOT RESERVED_NAME SEMICOLON SPACE START_MAIN STRING TYPE_INT TYPE_STRING VARIABLE XORmultispace : SPACE\n                  | SPACE multispace'
    
_lr_action_items = {'SPACE':([0,2,],[2,2,]),'$end':([1,2,3,],[0,-1,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'multispace':([0,2,],[1,3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> multispace","S'",1,None,None,None),
  ('multispace -> SPACE','multispace',1,'p_multispace','parse.py',7),
  ('multispace -> SPACE multispace','multispace',2,'p_multispace','parse.py',8),
]
